// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Curve.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface _CurveOperations
{
    void sayCurve(int delay, Ice.Current __current);

    float getDiscount(int date, Ice.Current __current);

    String[] getPillars(Ice.Current __current);

    void shutdown(Ice.Current __current);
}
