// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Curve.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface Curve extends Ice.Object,
                               _CurveOperations, _CurveOperationsNC
{
    public static final String ice_staticId = "::Demo::Curve";

    public static final long serialVersionUID = -2569902930424309079L;
}
